account/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from account import views

app_name = 'account'

urlpatterns = [
    # Add user dashboard url pattern
    path('dashboard/<str:username>/<int:pk>/', views.dashboard, name='dashboard'),
    # Add user registration url pattern
    path('register/', views.register, name='register'),
    # Add user edit url pattern
    path('dashboard/<int:pk>/edit/', views.edit, name='edit'),
]

stream/urls.py
from django.urls import path
from stream import views

app_name = 'stream'

urlpatterns = [
    # Add movie list url patterns
    path('movie-list/', views.movie_list, name='movie_list'),
    path('movie-list/<slug:category_slug>/', views.movie_list, name='movie_list_by_category'),
    # Add movie detail url pattern
    path('movies/<int:pk>', views.movie_detail, name='movie_detail'),
    # Add series list url patterns
    path('series-list/', views.series_list, name='series_list'),
    path('series-list/<slug:category_slug>/', views.series_list, name='series_list_by_category'),
    # Add series detail url pattern
    path('series/<int:pk>', views.series_detail, name='series_detail'),
    # Add season detail url pattern
    path('series/<int:series_pk>/season/<int:pk>', views.season_detail, name='season_detail'),
    # Add episode detail url pattern
    path('series/<int:series_pk>/season/<int:season_pk>/episode/<int:pk>', views.episode_detail, name='episode_detail'),

]

watchie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account import views

urlpatterns = [
    # Add django authentication url patterns
    path('', include('django.contrib.auth.urls')),
    # Include url patterns of account app
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    # Add default route
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    # Include url patterns of stream app
    path('stream/', include('stream.urls', namespace='stream')),
    # Include url patterns of payment app
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.urls import reverse
from multiselectfield import MultiSelectField


class User(AbstractUser):
    """
    Customize default user model to set email to a unique field
    """
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=200, unique=True)

    def get_absolute_url(self):
        # Create canonical url for detail view
        return reverse('account:dashboard', args=[self.pk, self.username])

    def __str__(self):
        return self.username


class Profile(models.Model):
    """
    Create profile model and associate one-to-one relationship with user model
    """
    ACTION = 'ACTION'
    ADVENTURE = 'ADVENTURE'
    BIOGRAPHY = 'BIOGRAPHY'
    COMEDY = 'COMEDY'
    CRIME = 'CRIME'
    HISTORY = 'HISTORY'
    HORROR = 'HORROR'
    DRAMA = 'DRAMA'
    SCIFI = 'SCIFI'
    FAVORITE_CHOICES = [
        (ACTION, 'Action'),
        (ADVENTURE, 'Adventure'),
        (BIOGRAPHY, 'Biography'),
        (COMEDY, 'Comedy'),
        (CRIME, 'Crime'),
        (HISTORY, 'History'),
        (HORROR, 'Horror'),
        (DRAMA, 'Drama'),
        (SCIFI, 'Sci-Fi'),
    ]
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    favorite = MultiSelectField(max_length=100, choices=FAVORITE_CHOICES, default=None, null=True, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='media/users', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.username} profile'


class Subscription(models.Model):
    """
    Create subscription model and associate one-to-one relationship with user model
    """
    TRIAL = 'TR'
    STANDARD = 'ST'
    PREMIUM = 'PR'
    SUBSCRIPTION_CHOICES = [
        (TRIAL, 'Trial'),
        (STANDARD, 'Standard'),
        (PREMIUM, 'Premium'),
    ]
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    code = models.UUIDField(default=uuid.uuid4, editable=False)
    type = models.CharField(max_length=2, choices=SUBSCRIPTION_CHOICES, default=TRIAL)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    active = models.BooleanField()

    def __str__(self):
        return str(self.type)

account/forms.py
from datetime import date, timedelta
from django import forms
from account.models import User, Profile, Subscription


class UserEditForm(forms.ModelForm):
    """
    Create user edit form to edit default user fields
    """
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name']


class LoginForm(forms.Form):
    """
    Create login form to authenticate users
    """

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    """
    Create register form to register new users
    """
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat Password", widget=forms.PasswordInput)

    class Meta:
        """
         Set form model and fields required rather than password and repeat password fields
        """
        model = User
        fields = ['username', 'email']

    def clean_password2(self):
        """
        Check if password and repeat password fields match and its pattern starts with clean_fieldname
        :return password2:
        """
        data = self.cleaned_data
        if data["password"] != data["password2"]:
            raise forms.ValidationError("Passwords don't match")
        return data["password2"]


class ProfileForm(forms.ModelForm):
    """
    Create profile model form
    """
    photo = forms.FileField(widget=forms.FileInput(attrs={'class': 'btn btn-primary'}))

    class Meta:
        model = Profile
        fields = ['date_of_birth', 'photo', 'favorite']
        widgets = {
            'date_of_birth': forms.widgets.DateInput(
                attrs={'type': 'date', 'class': 'form-control flatpickr flatpickr-input form-control active'})}

    def clean_date_of_birth(self):
        """
        Custom validation for date of birth
        :return validated date of birth:
        """
        if self.cleaned_data['date_of_birth'] is not None:
            date_of_birth = self.cleaned_data['date_of_birth']
            age = (date.today() - date_of_birth) // timedelta(days=365.2425)
            if age < 18:
                raise forms.ValidationError("Birthday is not allowed")
            return date_of_birth
        else:
            return None


class SubscriptionForm(forms.ModelForm):
    """
    Create subscription form
    """

    class Meta:
        """
        Registration should add trial subscription (14 days) with generated uuid of subscription code
        """
        model = Subscription
        fields = ['type']

account/views.py
import uuid
from datetime import timedelta
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from account.models import User, Profile, Subscription
from account.forms import RegistrationForm, ProfileForm, SubscriptionForm, UserEditForm
from account.helpers import is_subscription_active
from activity.helpers import create_activity
from activity.models import Activity


def index(request):
    """
    Create index view
    :param request:
    :return index template:
    """
    template = 'account/index.html'
    return render(request, template)


def register(request):
    """
    Create user registration view
    :param request:
    :return register template:
    """
    if request.method == 'POST':
        registration_form = RegistrationForm(data=request.POST)
        if registration_form.is_valid():
            new_user = registration_form.save(commit=False)
            # set password method handles password hashing
            new_user.set_password(registration_form.cleaned_data['password'])
            new_user.save()
            if request.user.id == new_user.id:
                create_activity(new_user, 'You registered you account successfully')
            template = "account/index.html"
            context = {"new_user": new_user}
            return render(request, template, context)
    else:
        user_form = RegistrationForm()
        template = "account/register.html"
        context = {"user_form": user_form}
        return render(request, template, context)


@login_required
def dashboard(request, username, pk):
    """
    Create user dashboard view
    :param request:
    :return dashboard template:
    """
    user = get_object_or_404(User, username=username, pk=pk)
    subscription = Subscription.objects.select_related('user').get(user__pk=pk)
    profile = Profile.objects.select_related("user").get(user__pk=pk)
    subscription_status = is_subscription_active(pk)
    last_day = timezone.now() - timedelta(hours=24)
    activities = Activity.objects.filter(user__pk=pk, created_at__gte=last_day)[:5]
    template = 'account/dashboard.html'
    context = {'user': user, 'subscription': subscription, 'profile': profile,
               'subscription_status': subscription_status, 'activities': activities}
    return render(request, template, context)


@login_required
def edit(request, pk):
    """
    Create user edit view
    :param request:
    :param pk:
    :return edit template:
    """
    user = get_object_or_404(User, pk=pk, is_active=True)
    if user:
        if request.method == 'POST':
            user_form = UserEditForm(data=request.POST, instance=request.user)
            profile_form = ProfileForm(data=request.POST, instance=request.user.profile, files=request.FILES)
            if user_form.is_valid() and profile_form.is_valid():
                user_form.save()
                profile_form.save()
                create_activity(request.user, 'You have updated your account successfully')
                messages.success(request, "Your profile has been updated successfully")
            else:
                messages.error(request, "An Error occurred while updating your profile")
        else:
            user_form = UserEditForm(instance=request.user)
            profile_form = ProfileForm(instance=request.user.profile)

        template = "account/edit.html"
        context = {'user_form': user_form, 'profile_form': profile_form}
        return render(request, template, context)
    return HttpResponse('Not Found')

account/templates/_messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            <span class="alert-inner--icon"><i class="ni ni-support-16"></i></span>
            <span class="alert-inner--text"><strong>Error!</strong>
                  {{ message }}
                </span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/brand/1.png' %}">
    <link rel="icon" type="image/png" href="{% static 'assets/img/brand/1.png' %}">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <!-- Nucleo Icons -->
    <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet"/>
    <!-- Font Awesome Icons -->
    <link href="{% static 'assets/css/font-awesome.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet"/>
    <!-- CSS Files -->
    <link href="{% static 'assets/css/argon-design-system.css' %}" rel="stylesheet"/>
    <!-- Video Player -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@clappr/player@latest/dist/clappr.min.js"></script>
    <script type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/@joaopaulo.vieira/clappr-media-control-plugin@latest/dist/clappr-media-control-plugin.min.js"></script>
</head>
<body class="index-page">
{{ redirect_to_login_immediately }}
<!-- Navbar -->
<nav id="navbar-main"
     class="navbar navbar-main navbar-expand-lg bg-white navbar-light position-sticky top-0 shadow py-2">
    <div class="container">
        <a class="navbar-brand mr-lg-5" href="{% url 'index' %}">
            <img src="{% static 'assets/img/brand/3.png' %}" style="height:80px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global"
                aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar_global">
            <div class="navbar-collapse-header">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{% url 'index' %}">
                            <img src="{% static 'assets/img/brand/blue.png' %}">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar_global"
                                aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <ul class="navbar-nav navbar-nav-hover align-items-lg-center">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link" data-toggle="dropdown" href="#" role="button">
                        <i class="ni ni-ui-04 d-lg-none"></i>
                        <span class="nav-link-inner--text">Stream</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-xl">
                        <div class="dropdown-menu-inner">
                            <a href="{% url 'stream:movie_list' %}"
                               class="media d-flex align-items-center">
                                <div class="icon icon-shape bg-gradient-primary rounded-circle text-white">
                                    <i class="ni ni-spaceship"></i>
                                </div>
                                <div class="media-body ml-3">
                                    <h6 class="heading text-primary mb-md-1">Movies</h6>
                                </div>
                            </a>
                            <a href="{% url 'stream:series_list' %}"
                               class="media d-flex align-items-center">
                                <div class="icon icon-shape bg-gradient-success rounded-circle text-white">
                                    <i class="ni ni-palette"></i>
                                </div>
                                <div class="media-body ml-3">
                                    <h6 class="heading text-primary mb-md-1">TV Series</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav align-items-lg-center ml-lg-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        Welcome back {{ reques.user.first_name|default:request.user.username|capfirst }}
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account:dashboard' request.user.username request.user.pk %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'logout' %}"> Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'account:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

{% block content %}
{% endblock %}
<footer class="footer">
    <div class="container">
        <div class="row row-grid align-items-center mb-5">
            <div class="col-lg-6">
                <h3 class="text-primary font-weight-light mb-2">Thank you for supporting us!</h3>
                <h4 class="mb-0 font-weight-light">Let's get in touch on any of these platforms.</h4>
            </div>
            <div class="col-lg-6 text-lg-center btn-wrapper">
                <button target="_blank" href="https://twitter.com/creativetim" rel="nofollow"
                        class="btn btn-icon-only btn-twitter rounded-circle" data-toggle="tooltip"
                        data-original-title="Follow us">
                    <span class="btn-inner--icon"><i class="fa fa-twitter"></i></span>
                </button>
                <button target="_blank" href="https://www.facebook.com/CreativeTim/" rel="nofollow"
                        class="btn-icon-only rounded-circle btn btn-facebook" data-toggle="tooltip"
                        data-original-title="Like us">
                    <span class="btn-inner--icon"><i class="fab fa-facebook"></i></span>
                </button>
                <button target="_blank" href="https://dribbble.com/creativetim" rel="nofollow"
                        class="btn btn-icon-only btn-dribbble rounded-circle" data-toggle="tooltip"
                        data-original-title="Follow us">
                    <span class="btn-inner--icon"><i class="fa fa-dribbble"></i></span>
                </button>
                <button target="_blank" href="https://github.com/creativetimofficial" rel="nofollow"
                        class="btn btn-icon-only btn-github rounded-circle" data-toggle="tooltip"
                        data-original-title="Star on Github">
                    <span class="btn-inner--icon"><i class="fa fa-github"></i></span>
                </button>
            </div>
        </div>
        <hr>
        <div class="row align-items-center justify-content-md-between">
            <div class="col-md-6">
                <div class="copyright">
                    &copy; 2023 <a href="" target="_blank">WATCHIE</a>.
                </div>
            </div>
            <div class="col-md-6">
                <ul class="nav nav-footer justify-content-end">
                    <li class="nav-item">
                        <a href="{% url 'index' %}" class="nav-link">Watchie</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link" target="_blank">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link" target="_blank">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link" target="_blank">License</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
</div>
<!--   Core JS Files   -->
<script src="{% static 'assets/js/core/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'assets/js/plugins/bootstrap-switch.js' %}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'assets/js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/plugins/moment.min.js' %}"></script>
<script src="{% static 'assets/js/plugins/datetimepicker.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/plugins/bootstrap-datepicker.min.js' %}"></script>
<!-- Control Center for Argon UI Kit: parallax effects, scripts for the example pages etc -->
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<script src="{% static 'assets/js/argon-design-system.min.js' %}" type="text/javascript"></script>
<script>
    function scrollToDownload() {

        if ($('.section-download').length != 0) {
            $("html, body").animate({
                scrollTop: $('.section-download').offset().top
            }, 1000);
        }
    }
</script>
<script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>
<script>
    window.TrackJS &&
    TrackJS.install({
        token: "ee6fab19c5a04ac1a32a645abde4613a",
        application: "argon-design-system-pro"
    });
</script>
</body>

</html>