payment/urls.py
from django.urls import path
from payment import views

app_name = 'payment'

urlpatterns = [
    # Add subscribe url pattern
    path('subscribe/', views.subscribe, name='subscribe'),
    path('standard-subscription/', views.standard_subscription, name='standard_subscription'),
    path('premium-subscription/', views.premium_subscription, name='premium_subscription'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),

]

stream/urls.py
from django.urls import path
from stream import views

app_name = 'stream'

urlpatterns = [
    # Add movie list url patterns
    path('movie-list/', views.movie_list, name='movie_list'),
    path('movie-list/<slug:category_slug>/', views.movie_list, name='movie_list_by_category'),
    # Add movie detail url pattern
    path('movies/<int:pk>', views.movie_detail, name='movie_detail'),
    # Add series list url patterns
    path('series-list/', views.series_list, name='series_list'),
    path('series-list/<slug:category_slug>/', views.series_list, name='series_list_by_category'),
    # Add series detail url pattern
    path('series/<int:pk>', views.series_detail, name='series_detail'),
    # Add season detail url pattern
    path('series/<int:series_pk>/season/<int:pk>', views.season_detail, name='season_detail'),
    # Add episode detail url pattern
    path('series/<int:series_pk>/season/<int:season_pk>/episode/<int:pk>', views.episode_detail, name='episode_detail'),

]

watchie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account import views

urlpatterns = [
    # Add django authentication url patterns
    path('', include('django.contrib.auth.urls')),
    # Include url patterns of account app
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    # Add default route
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    # Include url patterns of stream app
    path('stream/', include('stream.urls', namespace='stream')),
    # Include url patterns of payment app
    path('payment/', include('payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
import stripe
from decimal import Decimal

from django.contrib import messages
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from account.models import User, Subscription

# Load stripe api configuration
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


@login_required
def subscribe(request):
    """
    Create subscribe view
    :param request:
    :return:
    """
    user_id = request.user.id
    current_plan = Subscription.objects.get(user_id=user_id)
    template = 'payment/subscribe.html'
    context = {'current_plan': current_plan}
    return render(request, template, context)


@login_required
def standard_subscription(request):
    """
    Create standard subscription payment view
    :param request:
    :return:
    """
    user_id = request.user.id
    subscription_plan = Subscription(type=Subscription.STANDARD)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        session_data = {
            'mode': 'payment',
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        session_data['line_items'].append({
            'price_data': {
                'unit_amount': int(19 * Decimal('100')),
                'currency': 'usd',
                'product_data': {
                    'name': subscription_plan.get_type_display()+ ' ' + 'Subscription',
                },
            },
            'quantity': 1,
        })
        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/standard_subscription.html', locals())


@login_required
def premium_subscription(request):
    """
    Create premium subscription payment view
    :param request:
    :return:
    """
    user_id = request.user.id
    subscription_plan = Subscription(type=Subscription.PREMIUM)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        session_data = {
            'mode': 'payment',
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        session_data['line_items'].append({
            'price_data': {
                'unit_amount': int(39 * Decimal('100')),
                'currency': 'usd',
                'product_data': {
                    'name': subscription_plan.get_type_display() + ' ' + 'Subscription',
                },
            },
            'quantity': 1,
        })
        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/standard_subscription.html', locals())


def payment_completed(request):
    """
    Create successful payment view
    :param request:
    :return:
    """
    return render(request, 'payment/completed.html')


def payment_canceled(request):
    """
    Create canceled payment view
    :param request:
    :return:
    """
    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends 'base.html' %}
{% block title %}
    Payment Status
{% endblock %}
{% block content %}
    <h1 class="text-center">Payment Process Canceled or Failed</h1>
{% endblock %}

payment/templates/payment/completed.html
{% extends 'base.html' %}
{% block title %}
    Payment Status
{% endblock %}
{% block content %}
    <h1 class="text-center">Payment Process Successfully Completed</h1>
{% endblock %}

payment/templates/payment/subscribe.html
{% extends 'base.html' %}
{% block title %}
    Subscribe
{% endblock %}
{% block content %}
    {% include '_messages.html' %}
    <div class="section features-1">
        <div class="container ml-auto text-center">
            <div class="row text-center">
                <div class="col-md-8 mx-auto text-center">
                    <h3 class="display-3 mt--0">Watch movies and TV shows</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="info">
                        <div class="icon icon-lg icon-shape icon-shape-primary shadow rounded-circle">
                            <i class="ni ni-settings-gear-65"></i>
                        </div>
                        <h6 class="info-title text-uppercase text-primary">Trial Plan</h6>
                        <p class="description opacity-8">Trial Plan valid for 14 days</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="info">
                        <div class="icon icon-lg icon-shape icon-shape-primary shadow rounded-circle">
                            <i class="ni ni-single-copy-04"></i>
                        </div>
                        <h6 class="info-title text-uppercase text-primary">Standard Plan</h6>
                        <p class="description opacity-8">Watch movies only</p>
                        <b class="description opacity-8">$19.00/month</b>
                        <br>
                        <form action="{% url 'payment:standard_subscription' %}" method="post">
                            <input type="submit" value="Purchase now" class="btn btn-lg btn-primary">
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="info">
                        <div class="icon icon-lg icon-shape icon-shape-primary shadow rounded-circle">
                            <i class="ni ni-single-02"></i>
                        </div>
                        <h6 class="info-title text-uppercase text-primary">Premium Plan</h6>
                        <p class="description opacity-8">Watch movies and series</p>
                        <b class="description opacity-8">$39.00/month</b>
                        <br>
                        <form action="{% url 'payment:premium_subscription' %}" method="post">
                            <input type="submit" value="Purchase now" class="btn btn-lg btn-primary">
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}